#HHS Carrier
- Unique Identifier: HHS
  Enabled: True
  Carrier:
    Unique Identifier: HHS Carrier
    Position: 3
  Transport Device:
    Unique Identifier: CORE Gripper
    Home Config:
      Get:
      Place:
    Away Config:
      Get:
      Place:

- Unique Identifier: Lid Storage
  Enabled: True
  Carrier:
    Unique Identifier: Carrier 14
    Position: 1
  Transport Device:
    Unique Identifier: CORE Gripper
    Home Config:
      Get:
      Place:
    Away Config:
      Get:
      Place:

- Unique Identifier: Plate 1
  Enabled: True
  Carrier:
    Unique Identifier: Carrier 14
    Position: 3
  Transport Device:
    Unique Identifier: CORE Gripper
    Home Config:
      Get:
      Place:
    Away Config:
      Get:
      Place:

- Unique Identifier: Plate 2
  Enabled: True
  Carrier:
    Unique Identifier: Carrier 14
    Position: 4
  Transport Device:
    Unique Identifier: CORE Gripper
    Home Config:
      Get:
      Place:
    Away Config:
      Get:
      Place:

- Unique Identifier: Fliptube
  Enabled: True
  Carrier:
    Unique Identifier: FlipTube Carrier
    Position: 1
  Transport Device:
    Unique Identifier: CORE Gripper
    Home Config:
      Get:
      Place:
    Away Config:
      Get:
      Place:

- Unique Identifier: Reservoir
  Enabled: True
  Carrier:
    Unique Identifier: Reservoir Carrier
    Position: 1
  Transport Device:
    Unique Identifier: CORE Gripper
    Home Config:
      Get:
      Place:
    Away Config:
      Get:
      Place:
