#############################################################
#
# Devices: The pipetting devices available on this system. Options per device are different.
# Enabled: True: Can be used. False: Cannot be used
#
#############################################################

Microlab Star:
  Unique Identifier: Hammy
  Deck Layout Path: C:\Program Files (x86)\HAMILTON\Library\PytomatedLiquidHandling\Examples\Hal\SimpleDigestion\Layout\Layout_SimpleDigestion.lay
