Non-Moveable Carrier:
  - Unique Identifier: HHS Carrier
    Enabled: True
    DeckLoader Unique Identifier: Deck Loader
    Track Start: 1
    Track End: 5
    Num Labware Positions: 4
    Image Filename 3D: NA
    Image Filename 2D: NA

Autoload Carrier:
  - Unique Identifier: Carrier 14
    Enabled: True
    DeckLoader Unique Identifier: Deck Loader
    Labware ID: PLT_CAR_L5AC_A00_0001
    Track Start: 14
    Track End: 19
    Num Labware Positions: 5
    Image Filename 3D: NA
    Image Filename 2D: NA

  - Unique Identifier: FlipTube Carrier
    Enabled: True
    DeckLoader Unique Identifier: Deck Loader
    Labware ID: SMP_CAR_32_FlipTubes_A02_0001
    Track Start: 49
    Track End: 49
    Num Labware Positions: 1
    Image Filename 3D: NA
    Image Filename 2D: NA

  - Unique Identifier: Reservoir Carrier
    Enabled: True
    DeckLoader Unique Identifier: Deck Loader
    Labware ID: RGT_CAR5x50_53646_01_0001
    Track Start: 48
    Track End: 48
    Num Labware Positions: 1
    Image Filename 3D: NA
    Image Filename 2D: NA
