#############################################################
#
# Device IDs: This identifies the Device to users
# Enabled: True: Can be used. False: Cannot be used
# Com Port: Port to communicate with the Device
# Device Type: HeaterShaker or HeaterCooler
# Ambient Temp: Above ambient temp will heat, below ambient will cool. If device cannot cool then this is ignored
# Stable Temp Delta: If device temp is +- this value of set temp. Device is considered equilibrated and stable.
# Supported Plate Types: These are the plate supported by this device. This associates with the deck sequences file
# Plate Sequence: Sequence for that plate on the device
# Lid Sequence: Sequence for associated lid on the device
#
#############################################################

Transition Points:
  - Enabled: True
    Plate Sequence: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
    Plate Labware Unique Identifier: Corning Costar 2000uL 96 Well PCR Plate

Hamilton CORE Gripper:
  Unique Identifier: Gripper 1
  Enabled: True
  Backend Unique Identifier: Hammy
  Custom Error Handling: False
  Gripper Sequence: seq_COREGripTool
  Supported Labware Unique Identifiers:
    - Agilent Black Lid
    - Biorad 200uL 96 Well PCR Plate
    - Thermo 400uL 96 Well PCR Plate
    - Thermo 1200uL 96 Well PCR Plate
    - Corning Costar 2000uL 96 Well PCR Plate

  Supported Deck Locations Config:
    - Deck Location Unique Identifier: HHS
      Get Configuration:
      Place Configuration:
        CheckPlateExists: False

    - Deck Location Unique Identifier: Lid Storage
      Get Configuration:
      Place Configuration:
        CheckPlateExists: False

    - Deck Location Unique Identifier: Plate 1
      Get Configuration:
      Place Configuration:
        CheckPlateExists: False

    - Deck Location Unique Identifier: Plate 2
      Get Configuration:
      Place Configuration:
        CheckPlateExists: False
