#HHS Carrier
- Unique Identifier: HeaterShaker Position 1
  Enabled: True
  Transport Device:
    Unique Identifier: Gripper
    Home Config:
      Get: {}
      Place:
        CheckPlateExists: "No"
    Away Config:
      Get: {}
      Place:
        CheckPlateExists: "No"

#Carrier 14
- Unique Identifier: Carrier14_Pos3
  Enabled: True
  Transport Device:
    Unique Identifier: Gripper
    Home Config:
      Get: {}
      Place:
        CheckPlateExists: "No"
    Away Config:
      Get: {}
      Place:
        CheckPlateExists: "No"

- Unique Identifier: Carrier14_Pos5
  Enabled: True
  Transport Device:
    Unique Identifier: Gripper
    Home Config:
      Get: {}
      Place:
        CheckPlateExists: "No"
    Away Config:
      Get: {}
      Place:
        CheckPlateExists: "No"

#Carrier 48
- Unique Identifier: ReagentReserviorCarrier
  Enabled: True
  Transport Device:
    Unique Identifier: Gripper
    Home Config:
      Get: {}
      Place:
        CheckPlateExists: "No"
    Away Config:
      Get: {}
      Place:
        CheckPlateExists: "No"

- Unique Identifier: SpecialFlipTubeCarrier
  Enabled: True
  Transport Device:
    Unique Identifier: Gripper
    Home Config:
      Get: {}
      Place:
        CheckPlateExists: "No"
    Away Config:
      Get: {}
      Place:
        CheckPlateExists: "No"
