Transition Points:

Hamilton CORE Gripper:
  Unique Identifier: Gripper 1
  Enabled: True
  Backend Unique Identifier: Hammy
  Custom Error Handling: False
  Gripper Sequence: seq_COREGripTool
  Supported Labware Information:
    - Labware Unique Identifier: Agilent Black Lid
      Close Offset: 2
      Open Offset: 2
      Pickup Height: 4

    - Labware Unique Identifier: 200uL Biorad 96 Well PCR Plate
      Close Offset: 2
      Open Offset: 2
      Pickup Height: 4
