- Unique Identifier: Agilent Black Lid
  Enabled: True
  Dimensions:
    Long Side: 127
    Short Side: 86

- Unique Identifier: 200uL Biorad 96 Well PCR Plate
  Enabled: True
  Wells:
    Columns: 12
    Rows: 8
    Sequences Per Well: 1
    Max Volume: 225
    Dead Volume: 10
    Segment Equations:
      - Segment Height: 0
        Segment Equation: h * 12.3202

      - Segment Height: 14.68
        Segment Equation: h * 36.9605
  Dimensions:
    Long Side: 127
    Short Side: 86

- Unique Identifier: Hamilton 1.5mL FlipTube Special
  Enabled: True
  Wells:
    Columns: 1
    Rows: 32
    Sequences Per Well: 1
    Max Volume: 1500
    Dead Volume: 150
    Segment Equations:
      - Segment Height: 0
        Segment Equation: h * 12.3202

      - Segment Height: 14.68
        Segment Equation: h * 36.9605
  Dimensions:
    Long Side: 127
    Short Side: 86

#ENTRY
- Unique Identifier: 60mL Reagent Reservior
  Enabled: True
  Wells:
    Columns: 1
    Rows: 5
    Sequences Per Well: 8
    Max Volume: 50000
    Dead Volume: 2500
    Segment Equations:
      - Segment Height: 0
        Segment Equation: h * 12.3202

      - Segment Height: 14.68
        Segment Equation: h * 36.9605
  Dimensions:
    Long Side: 127
    Short Side: 86
