- Unique Identifier: Sample Plate
  Enabled: True
  Plate Sequence: PlatePosition1
  Plate Labware Unique Identifier: 200uL Biorad 96 Well PCR Plate
  Deck Location Unique Identifier: Carrier14_Pos3

- Unique Identifier: Digestion Plate
  Enabled: True
  Plate Sequence: PlatePosition3
  Plate Labware Unique Identifier: 200uL Biorad 96 Well PCR Plate
  Deck Location Unique Identifier: Carrier14_Pos5

- Unique Identifier: FlipTubes
  Enabled: True
  Plate Sequence: FlipTubes
  Plate Labware Unique Identifier: Hamilton 1.5mL FlipTube Special
  Deck Location Unique Identifier: SpecialFlipTubeCarrier

- Unique Identifier: Reagent Reservoirs
  Enabled: True
  Plate Sequence: ReagentReservoirs
  Plate Labware Unique Identifier: 60mL Reagent Reservior
  Deck Location Unique Identifier: ReagentReserviorCarrier
