NonTransportable DeckLocation:
  - Enabled: True
    Carrier Config:
      Carrier: Carrier39
      Position: 1

  - Enabled: True
    Carrier Config:
      Carrier: Carrier39
      Position: 2

  - Enabled: True
    Carrier Config:
      Carrier: Carrier39
      Position: 3

  - Enabled: True
    Carrier Config:
      Carrier: Carrier39
      Position: 4

  - Enabled: True
    Carrier Config:
      Carrier: Carrier39
      Position: 5
