NonTransportable DeckLocation:
  - Identifier: IMCS Tips Pos 1
    Enabled: True
    Carrier Config:
      Carrier: IMCS Tips
      Position: 1

  - Identifier: IMCS Tips Pos 2
    Enabled: True
    Carrier Config:
      Carrier: IMCS Tips
      Position: 2

  - Identifier: IMCS Tips Pos 3
    Enabled: True
    Carrier Config:
      Carrier: IMCS Tips
      Position: 3

  - Identifier: IMCS Tips Pos 4
    Enabled: True
    Carrier Config:
      Carrier: IMCS Tips
      Position: 4

  - Identifier: IMCS Tips Pos 5
    Enabled: True
    Carrier Config:
      Carrier: IMCS Tips
      Position: 5
