// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 9 1 0 "778771ab_7c3e_49e5_9d1974196ef28eab" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
DRIVER::Abort();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=BAREB$$valid=0$$time=2023-10-16 14:26$$checksum=f4826e95$$length=084$$