#############################################################
#
# Devices: The pipetting devices available on this system. Options per device are different.
# Enabled: True: Can be used. False: Cannot be used
#
#############################################################

Hamilton 96 Core Head:
  - Identifier: test
    Enabled: True
    Backend Identifier: Hammy
    Custom Error Handling: False

    Number of Channels: 96

    Supported Labware Identifiers:
      - 400uL Corning Costar 96 Well UV Plate
      - 200uL Biorad 96 Well PCR Plate
      - 400uL Thermo 96 Well PCR Plate
      - 1200uL DeepWell 96 Well PCR Plate
      - 2000uL Corning 96 Well PCR Plate

    Supported Deck Location Identifiers:
      - a
      - b

    Supported Tips:
      - Tip Identifier: 50uL NTR
        Tip Support Dropoff Sequence: Test
        Tip Support Pickup Sequence: Test
        Waste Sequence: Test

      - Tip Identifier: 300uL NTR
        Tip Support Dropoff Sequence: Test
        Tip Support Pickup Sequence: Test
        Waste Sequence: Test

      - Tip Identifier: 1000uL FTR
        Tip Support Dropoff Sequence: Test
        Tip Support Pickup Sequence: Test
        Waste Sequence: Test

    Supported Liquid Class Categories:
      - Identifier: Default
        Liquid Classes:
          - Identifier: Tip_50ul_Water_DispenseSurface_Empty
            Max Volume: 50

          - Identifier: StandardVolume_Water_DispenseSurface_Empty
            Max Volume: 300

          - Identifier: HighVolume_Water_DispenseSurface_Empty
            Max Volume: 1000

Hamilton 1mL Channels Portrait:
  - Identifier: Test
    Enabled: True
    Backend Identifier: Hammy
    Custom Error Handling: False

    Number of Channels: 8
    Active Channels: [1, 2, 3, 4, 5, 6, 7, 8]

    Supported Labware Identifiers:
      - 400uL Corning Costar 96 Well UV Plate
      - 200uL Biorad 96 Well PCR Plate
      - 400uL Thermo 96 Well PCR Plate
      - 1200uL DeepWell 96 Well PCR Plate
      - 2000uL Corning 96 Well PCR Plate
      - Hamilton 1.5mL FlipTube
      - 15mL Centrifuge Tube
      - 60mL Reagent Reservior
      - 200mL Reagent Trough

    Supported Deck Location Identifiers:
      - a
      - b

    Supported Tips:
      - Tip Identifier: 50uL NTR
        Tip Support Dropoff Sequence: Test
        Tip Support Pickup Sequence: Test
        Waste Sequence: Test

      - Tip Identifier: 300uL NTR
        Tip Support Dropoff Sequence: Test
        Tip Support Pickup Sequence: Test
        Waste Sequence: Test

      - Tip Identifier: 1000uL FTR
        Tip Support Dropoff Sequence: Test
        Tip Support Pickup Sequence: Test
        Waste Sequence: Test

    Supported Liquid Class Categories:
      - Identifier: Default
        Liquid Classes:
          - Identifier: Tip_50ul_Water_DispenseSurface_Empty
            Max Volume: 50

          - Identifier: StandardVolume_Water_DispenseSurface_Empty
            Max Volume: 300

          - Identifier: HighVolume_Water_DispenseSurface_Empty
            Max Volume: 1000
