#############################################################
#
# Device IDs: This identifies the Device to users
# Enabled: True: Can be used. False: Cannot be used
# Com Port: Port to communicate with the Device
# Device Type: HeaterShaker or HeaterCooler
# Ambient Temp: Above ambient temp will heat, below ambient will cool. If device cannot cool then this is ignored
# Stable Temp Delta: If device temp is +- this value of set temp. Device is considered equilibrated and stable.
# Supported Plate Types: These are the plate supported by this device. This associates with the deck sequences file
# Plate Sequence: Sequence for that plate on the device
# Lid Sequence: Sequence for associated lid on the device
#
#############################################################

Transition Points:
  - Enabled: True
    Plate Sequence: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
    Plate Labware Unique Identifier: 2000uL Corning 96 Well PCR Plate

Hamilton CORE Gripper:
  Unique Identifier: Gripper 1
  Enabled: True
  Backend Unique Identifier: a
  Custom Error Handling: False
  Gripper Sequence: seq_COREGripTool
  Supported Labware Unique Identifiers:
    - Agilent Black Lid
    - 200uL Biorad 96 Well PCR Plate
    - 400uL Thermo 96 Well PCR Plate
    - 1200uL DeepWell 96 Well PCR Plate
    - 2000uL Corning 96 Well PCR Plate
    - 400uL Corning Costar 96 Well UV Plate

  Supported Deck Locations Config:
    - Deck Location Unique Identifier:
      Get Configuration:
        Check Plate Exists: False
      Place Configuration:

Hamilton Internal Plate Gripper:
  Unique Identifier: Gripper 2
  Enabled: False
  Backend Unique Identifier: a
  Custom Error Handling: False
  Supported Labware Information:

  Supported Deck Locations Config:
    - Deck Location Unique Identifier:
      Get Configuration:
        GripMode:
        Movement:
        RetractDistance:
        LiftupHeight:
        LabwareOrientation:
        InverseGrip:

      Place Configuration:
        Movement:
        RetractDistance:
        LiftupHeight:
        LabwareOrientation:

Vantage Track Gripper:
  Unique Identifier: Gripper 3
  Enabled: False
  Backend Unique Identifier: a
  Custom Error Handling: False
  Supported Labware Information:
  Supported Deck Locations Config:
    - Deck Location Unique Identifier:
      Get Configuration:
        GripMode:
        Movement:
        RetractDistance:
        LiftupHeight:
        LabwareOrientation:
        InverseGrip:

      Place Configuration:
        Movement:
        RetractDistance:
        LiftupHeight:
        LabwareOrientation:
