Lid:
  - Identifier: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
    Enabled: True
    Sequence: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
    Labware Identifier: 2000uL Corning 96 Well PCR Plate
    Deck Location Identifier: Carrier38_Pos1

NonCoverable Item:
  - Identifier: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
    Enabled: True
    Sequence: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
    Labware Identifier: 2000uL Corning 96 Well PCR Plate
    Deck Location Identifier: Carrier38_Pos1

Coverable Item:
  - Identifier: Carrier38_Pos2_96WellPCRPlate2000uL_1mLChannel
    Enabled: True
    Sequence: Carrier38_Pos2_96WellPCRPlate2000uL_1mLChannel
    Labware Identifier: 2000uL Corning 96 Well PCR Plate
    Deck Location Identifier: Carrier38_Pos2
    Lid Identifier: Lid
