- Unique Identifier: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
  Enabled: True
  Plate Sequence: Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
  Plate Labware Unique Identifier: 2000uL Corning 96 Well PCR Plate
  Deck Location Unique Identifier: Carrier38_Pos1

- Unique Identifier: Carrier38_Pos2_96WellPCRPlate2000uL_1mLChannel
  Enabled: True
  Plate Sequence: Carrier38_Pos2_96WellPCRPlate2000uL_1mLChannel
  Plate Labware Unique Identifier: 2000uL Corning 96 Well PCR Plate
  Lid Sequence: Carrier14_Pos3_Lid_400uL
  Lid Labware Unique Identifier: Agilent Black Lid
  Deck Location Unique Identifier: Carrier38_Pos2
