#############################################################
#
# Rack IDs: This identifies the Rack to users
# Enabled: True: Can be used. False: Cannot be used
# Default Condense TIme: This is the condense time per 100uL if the chosen condense time is default
# Supported Labware: These are the plate supported by this Rack. This associates with the deck sequences file
# Plate Sequence: Sequence for that plate on the rack
# Supported Tips: The tips that can be used to pipette liquid. This is a tip ID from the pipette config
# Add Liquid Class: Liquid class that is used to add back liquid and mix the solution
# Remove Liquid Class: Liquid class that is used to remove all liquid without disturbance
#
#############################################################

- Unique Identifier: Rack 1
  Enabled: True
  Supported Labware Layout Item Unique Identifiers:
    - Item1
    - Item2

  Pipette Unique Identifiers:
    - Unique Identifier: 96 Head Hammy
      Liquid Classes:
        Remove Buffer:
          - Unique Identifier: Tip_50ul_Water_DispenseSurface_Empty
            Max Volume: 50

          - Unique Identifier: StandardVolume_Water_DispenseSurface_Empty
            Max Volume: 300

          - Unique Identifier: HighVolume_Water_DispenseSurface_Empty
            Max Volume: 1000

        Add Buffer:
          - Unique Identifier: Tip_50ul_Water_DispenseSurface_Empty
            Max Volume: 50

          - Unique Identifier: StandardVolume_Water_DispenseSurface_Empty
            Max Volume: 300

          - Unique Identifier: HighVolume_Water_DispenseSurface_Empty
            Max Volume: 1000
