#############################################################
#
# Device IDs: This identifies the Device to users
# Enabled: True: Can be used. False: Cannot be used
# Com Port: Port to communicate with the Device
# Device Type: HeaterShaker or HeaterCooler
# Ambient Temp: Above ambient temp will heat, below ambient will cool. If device cannot cool then this is ignored
# Stable Temp Delta: If device temp is +- this value of set temp. Device is considered equilibrated and stable.
# Supported Plate Types: These are the plate supported by this device. This associates with the deck sequences file
# Plate Sequence: Sequence for that plate on the device
# Lid Sequence: Sequence for associated lid on the device
#
#############################################################

Hamilton CORE Gripper:
  Identifier: Gripper
  Enabled: True
  Backend: Hammy
  Backend Error Handling: False
  Gripper Labware ID: seq_COREGripTool
  Supported Labwares:
    - Agilent Black Lid
    - 200uL Biorad 96 Well PCR Plate
    - 400uL Thermo 96 Well PCR Plate
    - 1200uL DeepWell 96 Well PCR Plate
    - 2000uL Corning 96 Well PCR Plate
    - 400uL Corning Costar 96 Well UV Plate

Hamilton Internal Plate Gripper:
  Identifier: Gripper 2
  Enabled: False
  Backend: a
  Backend Error Handling: False
  Supported Labwares:

Vantage Track Gripper:
  Identifier: Gripper 3
  Enabled: False
  Backend: a
  Backend Error Handling: False
  Supported Labwares:
