NonTransportable Deck Location:
  - enabled: True
    carrier_config:
      carrier: Carrier42
      position: 1

  - enabled: True
    carrier_config:
      carrier: Carrier42
      position: 2

  - enabled: True
    carrier_config:
      carrier: Carrier42
      position: 3

  - enabled: True
    carrier_config:
      carrier: Carrier42
      position: 4

  - enabled: True
    carrier_config:
      carrier: Carrier42
      position: 5
