Lid:
  - enabled: True
    labware_id: Carrier42_Pos1_Thermo400uL96WellPCR_Lid
    deck_location: Carrier42_Pos1
    labware: Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos2_Thermo400uL96WellPCR_Lid
    deck_location: Carrier42_Pos2
    labware: Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos3_Thermo400uL96WellPCR_Lid
    deck_location: Carrier42_Pos3
    labware: Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos4_Thermo400uL96WellPCR_Lid
    deck_location: Carrier42_Pos4
    labware: Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos5_Thermo400uL96WellPCR_Lid
    deck_location: Carrier42_Pos5
    labware: Thermo400uLPCRPlate_Lid

Coverable Plate:
  - enabled: True
    labware_id: Carrier42_Pos1_Thermo400uL96WellPCR
    deck_location: Carrier42_Pos1
    labware: Thermo400uLPCRPlate
    lid: Carrier42_Pos1_Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos2_Thermo400uL96WellPCR
    deck_location: Carrier42_Pos2
    labware: Thermo400uLPCRPlate
    lid: Carrier42_Pos2_Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos3_Thermo400uL96WellPCR
    deck_location: Carrier42_Pos3
    labware: Thermo400uLPCRPlate
    lid: Carrier42_Pos3_Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos4_Thermo400uL96WellPCR
    deck_location: Carrier42_Pos4
    labware: Thermo400uLPCRPlate
    lid: Carrier42_Pos4_Thermo400uLPCRPlate_Lid

  - enabled: True
    labware_id: Carrier42_Pos5_Thermo400uL96WellPCR
    deck_location: Carrier42_Pos5
    labware: Thermo400uLPCRPlate
    lid: Carrier42_Pos5_Thermo400uLPCRPlate_Lid
