Pipettable Labware:
  - Identifier: Hamilton1500uLFlipTubeCarrier
    Enabled: True
    Image Filename: N/A
    Part Number: "?"
    Wells:
      Layout:
        Type: Numeric
        Direction: Columnwise
        Columns: 1
        Rows: 32
      Positions Per Well: 1
      Max Volume: 1500
      Dead Volume: 10
      Segments:
        - Height: 16.1
          Equation: h * 20.2737

        - Height: 22
          Equation: h * 65.0624

    Dimensions:
      X Length: 0
      Y Length: 0
    Transport Offsets:
      Open: 0
      Close: 0
      Top: 0
      Bottom: 0
