
IMCS SizeX:
  Devices:
    - Unique Identifier: Position 1
      Enabled: True
      Backend Unique Identifier: Hammy
      Custom Error Handling: False

      Pipette Tips Config:
        Tip ID: 300uL NTR
        Tip Support:
          Drop Off Sequence: Carrier32_Pos1_TipSupportRack_300Standard_DropOff
          Pickup Sequence: Carier32_Pos1_TipSupportRack_Pickup_300Standard_Pickup
      
      IMCS Tips Config:
        Tip Support:
          Drop Off Sequence: Carrier32_Pos1_TipSupportRack_IMCSSizeX_DropOff
          Pickup Sequence: Carier32_Pos1_TipSupportRack_Pickup_IMCSSizeX_Pickup
        
        Rack:
          Drop Off Sequence: Carrier32_Pos5_IMCSTipsRack_DropOff
          Pickup Sequence: Carrier32_Pos5_IMCSTipsRack_Pickup

        Pipette Destination Sequence: Carrier32_Pos5_IMCSTips_PipetteDestination

  Elution Method Tip Types:
    - Unique Identifier: SizeX100
      Elution Methods:
        - Unique Identifier: MAM/Low Artifact
          Load Liquid Class: IMCS_Desalting_NTR
          Dispense Liquid Class: IMCS_SEC_T1_FastDispense
          Equilibration Dispense Height: 30
          Sample Dispense Height: 30
          Chaser Dispense Height: 30
          Equilibration Load Volume: 300
          Sample Load Volume: 100
          Chaser Load Volume: 100
          Equilibration Dispense Volume: 950
          Sample Dispense Volume: 150
          Chaser Dispense Volume: 150

        - Unique Identifier: HCP/Proteomics
          Load Liquid Class: IMCS_Desalting_NTR
          Dispense Liquid Class: IMCS_SEC_T1_FastDispense
          Equilibration Dispense Height: 30
          Sample Dispense Height: 30
          Chaser Dispense Height: 30
          Equilibration Load Volume: 300
          Sample Load Volume: 100
          Chaser Load Volume: 100
          Equilibration Dispense Volume: 950
          Sample Dispense Volume: 150
          Chaser Dispense Volume: 200

    - Unique Identifier: SizeX150
      Elution Methods:


        

