NonTransportable DeckLocation:
  - Identifier: Plates 3 Pos 1
    Enabled: True
    Carrier Config:
      Carrier: Plates 3
      Position: 1

  - Identifier: Plates 3 Pos 2
    Enabled: True
    Carrier Config:
      Carrier: Plates 3
      Position: 2

  - Identifier: Plates 3 Pos 3
    Enabled: True
    Carrier Config:
      Carrier: Plates 3
      Position: 3

  - Identifier: Plates 3 Pos 4
    Enabled: True
    Carrier Config:
      Carrier: Plates 3
      Position: 4

  - Identifier: Plates 3 Pos 5
    Enabled: True
    Carrier Config:
      Carrier: Plates 3
      Position: 5
