#############################################################
#
# Device IDs: This identifies the Device to users
# Enabled: True: Can be used. False: Cannot be used
# Com Port: Port to communicate with the Device
# Device Type: HeaterShaker or HeaterCooler
# Ambient Temp: Above ambient temp will heat, below ambient will cool. If device cannot cool then this is ignored
# Stable Temp Delta: If device temp is +- this value of set temp. Device is considered equilibrated and stable.
# Supported Labware: These are the plate supported by this device. This associates with the deck sequences file
# Plate Sequence: Sequence for that plate on the device
# Lid Sequence: Sequence for associated lid on the device
#
#############################################################

Hamilton Heater Shaker:
  - Identifier: Heater 1
    Enabled: True
    Backend: Hammy
    Backend Error Handling: False
    Com Port: 1
    Plates:
      - Item1
      - Item2

  - Identifier: Heater 2
    Enabled: True
    Backend Identifier: Hammy
    Backend Error Handling: False
    Com Port: 2
    Plates:
      - Item1
      - Item2
