Lid:
  - Enabled: True
    LabwareID: Carrier42_Pos1_Thermo400uL96WellPCR_Lid
    DeckLocation: Carrier42_Pos1
    Labware: Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos2_Thermo400uL96WellPCR_Lid
    DeckLocation: Carrier42_Pos2
    Labware: Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos3_Thermo400uL96WellPCR_Lid
    DeckLocation: Carrier42_Pos3
    Labware: Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos4_Thermo400uL96WellPCR_Lid
    DeckLocation: Carrier42_Pos4
    Labware: Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos5_Thermo400uL96WellPCR_Lid
    DeckLocation: Carrier42_Pos5
    Labware: Thermo400uLPCRPlate_Lid

Coverable Plate:
  - Enabled: True
    LabwareID: Carrier42_Pos1_Thermo400uL96WellPCR
    DeckLocation: Carrier42_Pos1
    Labware: Thermo400uLPCRPlate
    Lid: Carrier42_Pos1_Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos2_Thermo400uL96WellPCR
    DeckLocation: Carrier42_Pos2
    Labware: Thermo400uLPCRPlate
    Lid: Carrier42_Pos2_Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos3_Thermo400uL96WellPCR
    DeckLocation: Carrier42_Pos3
    Labware: Thermo400uLPCRPlate
    Lid: Carrier42_Pos3_Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos4_Thermo400uL96WellPCR
    DeckLocation: Carrier42_Pos4
    Labware: Thermo400uLPCRPlate
    Lid: Carrier42_Pos4_Thermo400uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier42_Pos5_Thermo400uL96WellPCR
    DeckLocation: Carrier42_Pos5
    Labware: Thermo400uLPCRPlate
    Lid: Carrier42_Pos5_Thermo400uLPCRPlate_Lid
