Lid:
  - enabled: True
    labware_id: _Vacuum_ManifoldHome
    deck_location: Carrier14_Pos3
    labware: VacuumManifoldShort

  - enabled: True
    labware_id: _Vacuum_ManifoldVacuum
    deck_location: Carrier14_Pos4
    labware: VacuumManifoldShort
