Lid:
  - Enabled: True
    LabwareID: Carrier48_Pos1_Thermo1200uL96WellPCR_Lid
    DeckLocation: Carrier48_Pos1
    Labware: ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos2_Thermo1200uL96WellPCR_Lid
    DeckLocation: Carrier48_Pos2
    Labware: ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos3_Thermo1200uL96WellPCR_Lid
    DeckLocation: Carrier48_Pos3
    Labware: ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos4_Thermo1200uL96WellPCR_Lid
    DeckLocation: Carrier48_Pos4
    Labware: ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos5_Thermo1200uL96WellPCR_Lid
    DeckLocation: Carrier48_Pos5
    Labware: ThermoAbgene1200uLPCRPlate_Lid

Coverable Plate:
  - Enabled: True
    LabwareID: Carrier48_Pos1_Thermo1200uL96WellPCR
    DeckLocation: Carrier48_Pos1
    Labware: ThermoAbgene1200uLPCRPlate
    Lid: Carrier48_Pos1_ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos2_Thermo1200uL96WellPCR
    DeckLocation: Carrier48_Pos2
    Labware: ThermoAbgene1200uLPCRPlate
    Lid: Carrier48_Pos2_ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos3_Thermo1200uL96WellPCR
    DeckLocation: Carrier48_Pos3
    Labware: ThermoAbgene1200uLPCRPlate
    Lid: Carrier48_Pos3_ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos4_Thermo1200uL96WellPCR
    DeckLocation: Carrier48_Pos4
    Labware: ThermoAbgene1200uLPCRPlate
    Lid: Carrier48_Pos4_ThermoAbgene1200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: Carrier48_Pos5_Thermo1200uL96WellPCR
    DeckLocation: Carrier48_Pos5
    Labware: ThermoAbgene1200uLPCRPlate
    Lid: Carrier48_Pos5_ThermoAbgene1200uLPCRPlate_Lid
