NonTransportable Deck Location:
  - enabled: True
    carrier_config:
      carrier: Carrier7
      position: 1

  - enabled: True
    carrier_config:
      carrier: Carrier7
      position: 2

  - enabled: True
    carrier_config:
      carrier: Carrier7
      position: 3

  - enabled: True
    carrier_config:
      carrier: Carrier7
      position: 4
