NonPipettable Labware:
  - Identifier: AgilentBlackLid
    Enabled: True
    Image Filename: LidAgilentBlack
    Part Number: TODO
    Dimensions:
      X Length: 136
      Y Length: 95
    Transport Offsets:
      Open: 2
      Close: 2
      Top: 4
      Bottom: 4

Pipettable Labware:
  - Identifier: Biorad200uL96WellPCRPlate
    Enabled: True
    Image Filename: PlateBiorad200uL96Well
    Part Number: HSP9601
    Wells:
      Layout:
        Type: AlphaNumeric
        Direction: Columnwise
        Columns: 12
        Rows: 8
      Positions Per Well: 1
      Max Volume: 200
      Dead Volume: 10
      Segments:
        - Height: 0
          Equation: h * 2.3562

        - Height: 15
          Equation: h * 14.5953
    Dimensions:
      X Length: 127
      Y Length: 86
    Transport Offsets:
      Open: 2
      Close: 2
      Top: 4
      Bottom: 4
