NonPipettable Labware:
  - Identifier: Agilent Black Lid
    Enabled: True
    Image Filename: LidAgilentBlack
    Part Number: TODO
    Dimensions:
      X Length: 136
      Y Length: 95
    Transport Offsets:
      Open: 2
      Close: 2
      Top: 4
      Bottom: 4

Pipettable Labware:
  - Identifier: Biorad 200uL 96 Well PCR Plate
    Enabled: True
    Image Filename: PlateBiorad200uL96Well
    Part Number: HSP9601
    Wells:
      Addressing:
        Type: AlphaNumeric
        Direction: Columnwise
      Columns: 12
      Rows: 8
      Sequences Per Well: 1
      Max Volume: 200
      Dead Volume: 10
      Segments:
        - Height: 0
          Equation: h * 2.3562

        - Height: 15
          Equation: h * 14.5953
    Dimensions:
      X Length: 127
      Y Length: 86
    Transport Offsets:
      Open: 2
      Close: 2
      Top: 4
      Bottom: 4
