Lid:
  - Enabled: True
    LabwareID: HHS_Pos1_Biorad200uL96WellPCR_Lid
    DeckLocation: Carrier7_Pos1
    Labware: Biorad200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: HHS_Pos2_Biorad200uL96WellPCR_Lid
    DeckLocation: Carrier7_Pos2
    Labware: Biorad200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: HHS_Pos3_Biorad200uL96WellPCR_Lid
    DeckLocation: Carrier7_Pos3
    Labware: Biorad200uLPCRPlate_Lid

Coverable Plate:
  - Enabled: True
    LabwareID: HHS_Pos1_Biorad200uL96WellPCR
    DeckLocation: Carrier7_Pos1
    Labware: Biorad200uLPCRPlate
    Lid: Carrier7_Pos1_Biorad200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: HHS_Pos2_Biorad200uL96WellPCR
    DeckLocation: Carrier7_Pos2
    Labware: Biorad200uLPCRPlate
    Lid: Carrier7_Pos2_Biorad200uLPCRPlate_Lid

  - Enabled: True
    LabwareID: HHS_Pos3_Biorad200uL96WellPCR
    DeckLocation: Carrier7_Pos3
    Labware: Biorad200uLPCRPlate
    Lid: Carrier7_Pos3_Biorad200uLPCRPlate_Lid
