#############################################################
#
# Devices: The pipetting devices available on this system. Options per device are different.
# Enabled: True: Can be used. False: Cannot be used
#
#############################################################

Hamilton FlipTube:
  - Identifier: Fliptube 1
    Enabled: True
    Backend Identifier: Hammy
    Custom Error Handling: False
    Tool Layout Labware ID: Ham_4_FlipTubeTools_OnWaste_0001
    Tool Layout Position ID: 1
    Supported Labware Identifiers:
      - Hamilton 1.5mL FlipTube
    Supported Deck Location Identifiers:
      - a
      - b
      - c

Hamilton FlipTube Special:
  - Identifier: Fliptube 1
    Enabled: True
    Backend Identifier: Hammy
    Custom Error Handling: False
    Tool Layout Labware ID: Ham_4_FlipTubeTools_OnWaste_0001
    Tool Layout Position ID: 1
    Supported Labware Identifiers:
      - Hamilton 1.5mL FlipTube
    Supported Deck Location Identifiers:
      - a
      - b
      - c
