NonTransportable DeckLocation:
  - Identifier: Vacuum Storage Pos 1
    Enabled: True
    Carrier Config:
      Carrier: Vacuum
      Position: 1

  - Identifier: Vacuum Storage Pos 2
    Enabled: True
    Carrier Config:
      Carrier: Vacuum
      Position: 2

  - Identifier: Vacuum Manifold Park
    Enabled: True
    Carrier Config:
      Carrier: Vacuum
      Position: 3

  - Identifier: Vacuum Manifold Vacuum
    Enabled: True
    Carrier Config:
      Carrier: Vacuum
      Position: 4
