Hamilton Vacuum:
  - Identifier: Vacuum 1
    Enabled: True
    Backend: Hammy
    Custom Error Handling: True
    Com Port: COM1
    Max Pressure: 1000
    Manifold Park:
    Manifold Processing:
    Supported Filter Plate Configurations:
      - Filter Plate Stack:
        Collection Plate:
        Default Vacuum Pressures:
          Low:
          Medium:
          High:
