#HHS Carrier
- Identifier: HHS_Carrier_Pos1
  Enabled: True
  Carrier:
    Identifier: C1
    Position: 1
  Transport Config:
    Transport Device Identifier: Gripper

- Identifier: HHS_Carrier_Pos2
  Enabled: True
  Carrier:
    Identifier: C1
    Position: 1

- Identifier: HHS_Carrier_Pos3
  Enabled: True
  Carrier:
    Identifier: C1
    Position: 1

- Identifier: HHS_Carrier_Pos4
  Enabled: True
  Carrier:
    Identifier: C1
    Position: 1

#Vacuum Carrier
- Identifier: Vacuum_Carrier_Pos1
  Enabled: True
  Carrier:
    Identifier: C1
    Position: 1
