#HHS Carrier
- Unique Identifier: HHS_Carrier_Pos1
  Enabled: True
  Carrier:
    Unique Identifier: C1
    Position: 1

- Unique Identifier: HHS_Carrier_Pos2
  Enabled: True
  Carrier:
    Unique Identifier: C1
    Position: 1

- Unique Identifier: HHS_Carrier_Pos3
  Enabled: True
  Carrier:
    Unique Identifier: C1
    Position: 1

- Unique Identifier: HHS_Carrier_Pos4
  Enabled: True
  Carrier:
    Unique Identifier: C1
    Position: 1

#Vacuum Carrier
- Unique Identifier: Vacuum_Carrier_Pos1
  Enabled: True
  Carrier:
    Unique Identifier: C1
    Position: 1
