
#HHS Carrier
- Unique Identifier: HHS_Carrier_Pos1
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

- Unique Identifier: HHS_Carrier_Pos2
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

- Unique Identifier: HHS_Carrier_Pos3
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

- Unique Identifier: HHS_Carrier_Pos4
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

#Vacuum Carrier
- Unique Identifier: Vacuum_Carrier_Pos1
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

- Unique Identifier: Vacuum_Carrier_Pos2
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

- Unique Identifier: Vacuum_Carrier_Pos3
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

- Unique Identifier: Vacuum_Carrier_Pos4
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:

#Carrier 14
- Unique Identifier: Carrier14_Pos1
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier14_Pos2
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier14_Pos3
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier14_Pos4
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier14_Pos5
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

#Carrier 14
- Unique Identifier: Carrier38_Pos1
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier38_Pos2
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier38_Pos3
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier38_Pos4
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

- Unique Identifier: Carrier38_Pos5
  Enabled: True
  Supported Transport IDs:
    CORE Gripper:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

#Carrier 47
- Unique Identifier: FalconTubeCarrier
  Enabled: True
  Supported Transport IDs:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

#Carrier 48
- Unique Identifier: ReagentReserviorCarrier
  Enabled: True
  Supported Transport IDs:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"

#Carrier 49
- Unique Identifier: FlipTubeCarrier
  Enabled: True
  Supported Transport IDs:
  Deck Loading:
    Carrier Labware String: Test
    Carrier Track Start: 1
    Carrier Track End: 1
    Carrier Type: FTRCarrier5Position
    Carrier Positions: "1"
